name: Amul Bot

on:
  schedule:
    - cron: '0 * * * *'  # every 1 hour
  workflow_dispatch:  # allows manual triggering

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t amul-bot .

      - name: Run Docker container
        run: docker run --rm -v $(pwd):/app amul-bot python amul.py --github-actions