name: Amul Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # every 30 minutes
  workflow_dispatch:  # allows manual triggering

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t amul-bot .

      - name: Run Docker container
        run: docker run --rm -v $(pwd):/app amul-bot python amul.py --github-actions

      - name: Commit state
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "amul-bot"
          git config --global user.email "amul-bot@github.com"
          git remote set-url origin https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add amul_state.json
          git diff --cached --quiet || git commit -m "Update Amul product state [skip ci]"
          git push 